language: java

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
  
jdk:
- openjdk11

install: true
    
addons:
  sonarcloud:
    organization: "qsestest" # the key of the org you chose at step #3
    token: $SONAR_TOKEN
      
script:
  - mvn compile spotbugs:spotbugs sonar:sonar -Dsonar.projectKey=qsestest_WebGoat
